----------------------------------------------------------------------
-- ClassicClassesEnhanced — Lore Data
--
-- Brief lore descriptions for enhanced classes, sourced from
-- the Warcraft Wiki (warcraft.wiki.gg).
----------------------------------------------------------------------

CCE = CCE or {}

----------------------------------------------------------------------
-- Lore text per character (sourced from warcraft.wiki.gg)
----------------------------------------------------------------------
CCE.LoreData = {

    ["Apothecary"] = "The Royal Apothecary Society is an alchemical society created by Lady Sylvanas Windrunner in order to create a new undead plague to wipe out the Scourge. Once based in the Apothecarium in Undercity, its members are all Forsaken or other types of undead beings who are constantly brewing up new plagues and poisons to unleash upon their enemies. The other races of the Horde believe they are working on a remedy to cure their illness.",

    ["Beastmaster"] = "Beastmasters are hunters who devote their lives to commanding powerful wild beasts. They reject civilized firearms. Their pets are brothers, not tools — and their death is permanent. Beastmasters are drawn to the perilous primal world, invigorated by its dangerous and untamed nature. They seek to hunt the biggest and most challenging game.",

    ["Prospector"] = "Subterranean realms demand a different sort of scout. Prospectors focus their efforts on the dark, enclosed places underground, which allows them to triumph in all dungeonlike areas. They wander the world searching for untapped veins of ore. Dwarven prospectors are proficient with all simple and martial weapons, and light armor. They are valuable trackers and ambushers.",

    ["Bloodmage"] = "Blood mages are blood elves adept at controlling fire magic. While they were still members of the Alliance resistance, the blood elves began to turn to the darkest parts of magic, disregarding the water and frost spells of the Kirin Tor for the fire and heat of what some people fear to be demonic magic. They are master enchanters and travel with phoenix companions. The blood elves that are fallen victim to the Scourge have joined the Forsaken, hence, the Forsaken have some bloodmages in their ranks as well.",

    ["Elven Archer"] = "Elven Archers of the Night Elves are elite ranged combatants specializing in archery, tracking, and woodland warfare. Turning to nature itself for aid, they possess minor druidic abilities expressed in their traps. They operate as solo, without animal pets.",

    ["Buccaneer"] = "Buccaneers are seafaring combatants who sail between ports, taming jungle beasts and wielding guns alongside rapiers. They live by the pirate's code, answering to no crown, with a parrot on one shoulder and a cutlass in hand. They also love fishing.",

    ["Death Knight"] = "Originally created by Gul'dan during the Second War as souls of orc warlocks placed into the bodies of fallen human knights. These Death Knights command necrotic magic (drain spells), skeletal steeds, and hit with their truncheons. During the Third War, the Lich King Ner'zhul created a new breed of death knights: malevolent, rune-wielding warriors of the Scourge. Unlike Gul'dan's creations, these modern death knights were created mainly from human paladins who lost their faith and pledged themselves to the Lich King in exchange for immortality.",

    ["Demon Hunter"] = "Demon hunters, the disciples of Illidan Stormrage, uphold a dark legacy, one that frightens their allies and enemies alike. The Illidari embrace fel and chaotic magics — energies that have long threatened the world of Azeroth — believing them necessary to challenge the Burning Legion. They fight against the forces of Chaos using their own terrible powers against it. They wield twin blades shirtless and operate outside traditional society.",

    ["Druid of the Claw"] = "The Druids of the Claw are a clan of druids charged with the protection of Val'sharah from any that would seek to disrupt the balance of nature. Druids of the Claw are masters of their mighty animal forms. When they transform into bears, they become ferocious physical combatants and protectors of nature. They were woken up from their centuries-long hibernation by Malfurion Stormrage in the Barrow Deeps and were rallied to fight in the Battle of Mount Hyjal during the Third War. They live a secluded life, rarely going  into towns or cities and therefore not using the amenities. They fight against the Venture Company who seek to mine and exploit Azeroth's nature.",

    ["Earthcaller"] = "Earthcallers are mighty warrior shamans who embrace the spirits to assist them in battles. They strengthen their spiritual connection until they can feel the spirits of the earth flowing within their body and thoughts, strengthening their arms and quickening their minds. Whispered fragments impart insight into battle as ancestors speak of ways to overcome all foes. Earthcallers have mastery of elemental earth, the toughest and strongest of the elements. Similar to their element of choice, they wear strong and durable armor and shields.",

    ["Exemplar"] = "Battlefields are bloody places, but they are also the proving grounds of heroes. Among the many legendary feats of bravery are the deeds of the exemplars: men and women who strike fear into the hearts of their enemies through intimidation and demoralization. They also inspire courage in their allies, holding their banners high and charging into battle, shouting encouragement to those who ride beside them. To be an exemplar is to sacrifice a great deal of freedom in pursuit of a path that's narrower than a warrior's or paladin's. They are living symbols of faith and justice, wearing guild tabards and Stormwind colors as ordained protectors of the innocent.",

    ["Techno-mage"] = "Techno-mages are arcane scholars who combine their magical knowledge with the use of technology. They are primarily gnomes, and wear advanced goggles that enhance their arcane sight. Following the Battle for Broken Shore, Gnomeregan Mechano-Mages were deployed during the Legion Invasions. Once saved by Alliance adventurers, they summoned Mechano-Peeps and helped fight the demonic invaders.",

    ["Mountain King"] = "The mountain kings, or thanes as they are known in Khaz Modan, are the mightiest dwarven warriors under the mountain. Wielding warhammers, hand axes, and shields, these fierce fighters live to test themselves against worthy opponents. Unconcerned with their race's preoccupation with mechanical devices and mining precious minerals, Mountain Kings live only for battle. Dedicated to safeguarding the Alliance which saved their kingdom during the Second War, the mountain kings can be counted upon to rally behind any banner that stands between freedom and the ever-looming shadow of evil.",

    ["Mountaineer"] = "Mountaineers are dwarven rangers using custom-built rifles and massive axes. They are mostly found in Khaz Modan, but they often travel wide and seek out quests that bring glory to Ironforge. They are a prized division of the Ironforge Army, and have fought in many battles. Most mountaineers wear green uniforms, but a few have been spotted wearing a purple or yellow uniform.",

    ["Necromancer"] = "These insidious magicians were once thought to be aspiring geniuses by the Magocracy of Dalaran. However, their insatiable lust to delve into the secrets of the dark arts drove them to forsake their very souls. Ner'zhul, the Lich King, granted these malevolent sorcerers true power over life in exchange for their loyalty and obedience. An aspiring Necromancer may still be learning to raise the dead, but they have perfected their ability to drain life from the living. Necromancers are not Warlocks, hence, they cannot summon demons.",

    ["Plagueshifter"] = "Few forces have devastated the world as badly as plague. The Plaguelands of Lordaeron are a testament to the ravages that disease can bring to the world. After long and careful deliberation the Horde formed a new order of druids, the plagueshifters, who were charged with reclaiming the Plaguelands and other stricken areas. Plagueshifters study the plague and other diseases to eradicate them wherever they fester.",

    ["Priestess of the Moon"] = "The priestesses of the moon are the women who make up the elite night elf clergy, the Sisterhood of Elune. They epitomize the power and grace of Elune, their race's ancient moon goddess. They ride the fearless frostsabers into battle. Charged with the safekeeping of the night elf lands and armed with magical energy — the priestesses of the moon will stop at nothing to rid their ancient land of evil.",

    ["Pyremaster"] = "Orcs burn their dead. In a world filled with magic, magic insinuates itself in ritual. Founded in the mysteries of certain cults on Draenor, the pyremaster is the enactor of ritual. This funerary priest guides the dead through fire, through loss of flesh, so their naked spirits may conquer the elements; in order to protect his duties and his person, he commands and fire. They are associated with orcish shamanic traditions, hence, they ride wolves and don't summon shadow demons or use wands.",

    ["Blademaster"] = "In the orc society, blademasters are known as legendary warriors of the Burning Blade clan. Sticky, smelly, and highly flammable, blazegrease is liberally applied to the swords and axes of the Burning Blade clan before battle. Though some choose to ignite their weapons before battle, most let the inevitable contact of blades and armor spark the blazegrease for unpredictable intimidation. By drawing on the anger of the spirits, an experienced Blademaster can strike their enemies dead instantly.",

    ["Savagekin"] = "The most primal of druids, savagekin bear an ancient but obscure legacy. Whereas some druids seek to command nature or bond with it, the savagekin surrenders himself to the natural world, abandoning much of their humanity to live with the beasts. Savagekin are druids who spend most of their time in animal form. As animals they gain strength and finesse, but come close to becoming irreversibly feral. Savagekin constantly battle the inner beasts that threaten to consume them, clinging to their last vestiges of sentience.",

    ["Shadow Hunter"] = "Shadow hunters are reclusive and wily masters of voodoo and shadow magic and were once the highest authority amongst trolls and their respective warbands. Their spirit powers can both heal and curse, walking the line of dark and light in hope of saving the future of trollkind, doing whatever it takes to secure a future for their kin. The loa can channel themselves through the shadow hunters when they use their ceremonial rush'kah masks. They aren't traditional spellcasters - they can also dish out powerful melee strikes.",

    ["Scarlet Champion"] = "The Scarlet Crusade is a fanatical religious sect dedicated to the eradication of the undead from Lordaeron. Similarly to the Argent Dawn, the Crusade evolved from the Order of the Silver Hand in the aftermath of the Third War. While the Argent Dawn maintained the Silver Hand's original compassionate ideals by welcoming all races to fight the Scourge neutrally, the Scarlet Crusade devolved into a fanatical, xenophobic cult manipulated by outside forces. You were raised in the Scarlet Crusade but are now becoming aware of its corruption and twisted ethics.",

    ["Spiritwalker"] = "Spiritwalkers are mystical, white-furred tauren casters who travel far and wide to find kindred spirits. They carry lanterns to light shadowed spirit paths. Believed to be the ill omen of a coming age, white tauren are held in near reverence by their people in Kalimdor, often becoming reclusive shamans. Spiritwalkers maintain the balance between the world of the living and the spirit realm. They can travel into the memories of the dead to glean clues about the past.",

    ["Templar"] = "Templars are a type of religious combatants. They can be skilled in battle or invaluable as support units. They are also the most righteous in their demeanor. Strength of arms or purity of mind are strict requirements. Templar paladins and priests stop at nothing to fulfill their divine purpose of bringing justice and purging the wicked. They wield the Light and unleash devastating combinations of Physical or Holy attacks that vanquish their enemies. They are sworn to protect the living against undead corruption. They carry the Argent Dawn's trinket as proof of their sacred oath.",

    ["Brewmaster"] = "Brewmasters (also known as brewmeister or brewmaiden) are masters of crafting drinks and concoctions that grant special abilities to themselves and others. As sturdy brawlers who use liquid fortification and unpredictable movement to avoid damage and protect allies, they may seem to struggle with balance as they chug their concoctions in the middle of a fight, but this unpredictable behavior is far from foolhardiness. Brewmasters combine martial prowess with brewing mastery. They use staves to fight, and wear robes as well as exotic armor.",

    ["Spellblade"] = "Spellblades are spellcasters who accompany soldiers into the heart of battle. The generations of warfare on Azeroth have given spellblades time to hone useful spells into simple and secret rituals, called battlemagics, which are passed from spellblades to another. They can wield a sword in one hand, and a staff in the other. As spellblades accompany warriors into battle, they become better at defending themselves than other wizards. They fight on the front lines alongside footmen using frost magic to crowd control.",

    ["Witch Doctor"] = "Witch doctors are spellcasters and alchemists. Troll witch doctors utilize voodoo, arcane, shadow and nature magic, while augmenting their abilities with juju, mojo and muisek. Ancestral staves and Rush'kah masks are used by witch doctors to call upon their ancestors and loa. They often use the smoke herbs to draw evil from its hiding places.",

    ["Runemaster"] = "Runemasters are monk-like melee fighters who draw upon the primal energies of the land, inscribing runes of power onto their flesh and weapons. The runemaster is a free spirit, more at home in the wild than in the city. Runemasters reject heavy armor and defensive stances, believing that hesitation dishonors the ancestors. They are protectors of nature and ley lines.",

    ["Berserker"] = "Troll berserkers are fearsome warriors who enter frenzied rages in battle, hacking through enemies with axes, blades, and daggers while hurling throwing weapons at distant foes. Berserkers fight with extreme ferocity and little regard for self-preservation. They are known for their strength, aggressive behavior in battle, and, sometimes, fighting with little to no armor. The berserker tradition traces back to the ancient Gurubashi Empire, where the fiercest warriors proved their worth through sheer savagery.",

    ["Brave"] = "Braves are the frontline defenders of the tauren people, warriors who have proven their courage through rites of passage on the open plains of Mulgore. Armed with polearms and wearing war harnesses instead of heavy plate, they embody the martial traditions of the Horde's most honorable race. A brave fights not for glory but for the safety of the tribe, standing firm against quilboar, centaur, and any who threaten the grasslands.",

    ["Tinker"] = "Tinkers are gnomish combat engineers who take their inventions into the field. Armed with maces and guns of their own design, they wear an ever-evolving array of goggles and deploy experimental gadgets like discombobulator rays in the heat of battle. Tinkers believe that any problem can be solved with the right gadget, and if the gadget explodes, well, that just means it needs more testing.",

    ["Warden"] = "Wardens are the elite night elf jailers and hunters who once guarded Illidan Stormrage in his prison beneath Hyjal. When a prisoner escapes, the wardens track them relentlessly across any distance. Masters of subtlety who fight with daggers and thrown weapons, they wear robes and long cloaks as they pursue their quarry. A warden never abandons the hunt.",

    ["Wilderness Stalker"] = "Wilderness stalkers are troll hunters who survive on instinct alone, drifting through the wild places of Azeroth with no permanent home. They favor thrown weapons and dual axes over bows, tracking prey through jungles and deserts alike. No one can match a wilderness stalker for their ability to survive in harsh environments. Wilderness stalkers claim that the lands speak to them, aiding them in their hunting and protecting them.",

    ["Lightslayer"] = "Lightslayers are Forsaken shadow priests who have fully rejected the Holy Light that sustained them in life. Where other undead priests cling to fading memories of faith, lightslayers embrace the void with fervor, wielding shadow magic and cursed daggers against the living and the Scarlet Crusade alike. They operate in darkness, drawing power from the very absence of light.",

    ["Hedge Wizard"] = "Hedge wizards are self-taught mages who never attended the academies of Dalaran. They learn their craft through trial and error, folklore, and stolen scraps of arcane knowledge. Unable to use arcane spells, they compensate with raw fire magic and cunning. Hedge wizards travel with pet snakes and maintain a suspicious interest in Dalaran, often lurking near its borders.",

    ["Sister of Steel"] = "In this time of conflict, members of both genders take up sword and axe and shield and march to the frontlines. However, due to a long tradition, more men than women become soldiers. As conflicts continue, men become noticeably scarcer in Stormwind, Ironforge, and other Alliance cities. More and more, women perform the tasks traditionally reserved for men, such as working at the forge. The sisters of steel are just such a group of female blacksmiths. Long experience at the forge toughens the sisters' skin and strengthens their muscles to the point where they can plunge their hands into fire without wincing, and blades rebound from their flesh. When the need arises, the sisters of steel lift the weapons they forged and move out to combat their enemies.",

    ["Dragonsworn"] = "For centuries, the great dragonflights have noted the potential of younger races. In a few select cases, they choose a creature of another race to be one of a select few with the privilege of directly serving a dragon or an entire group of dragons. Such devotees dedicate their lives to the protection and service of their dragonflights and reap the benefits of the great knowledge and power that their draconic masters share.",

    ["Kirin Tor Mage"] = "Kirin Tor Mages study to be the most powerful human mages on Azeroth. Masters of frost and fire magic, they wear the distinctive violet robes and circlets of their order while carrying enchanted staves. Archmages dedicate their lives to the study and regulation of magic, defending the world against arcane threats while expanding the boundaries of magical knowledge.",

    ["Ley Walker"] = "Ley walkers are casters who study ley lines that crisscross beneath Azeroth's surface. Part naturalist, part arcanist, they channel the raw magical energy of the world itself through elemental robes of power. Their obsession with intellect and arcane potency sets them apart from traditional casters, walking a path that blurs the line between nature magic and the arcane.",

    ["Barbarian"] = "Barbarians are fierce and primal warriors embodying strength and tribal instincts in battle. They are uncivilized and brutal, relying on anger and raw physical might instead of tactics or fancy swordsmanship. Their rage is frightening to behold, and it allows them to smash apart his enemies while ignoring all but the most brutal blows.",

    ["Ranger"] = "Rangers are skilled ranged combatants specializing in wilderness survival and exploration. Humans always employed rangers, Nathanos Marris, for instance, was a ranger in the service of Lordaeron, having worked his way up to the rank of Ranger Captain. After the Fall of Quel'Thalas, Arthas Menethil raised fallen elven Farstriders into Darkfallen dark rangers, who eventually joined Sylvanas Windrunner and the Forsaken.",

    ["Druid of the Wild"] = "Druid of the Wild is a class of druid which incorporates many different animals and animalistic aspects into their repertoire. They are tied to the living aspects of nature — flora and fauna. After the Legion's invasion, the druids began to use the powers of all forms, combining their strengths against their enemies and becoming the druids of the wild. Ysera is the absolute ruler of the Emerald Dream. As such, most druids of the wild venerate her; and even if some do not treat her as a deity, she is at least acknowledged as one of the greatest paragons of nature in existence.",

    ["Shieldbearer"] = "Shieldbearers use holy magic to shield themselves and defend allies from attackers. With plate armor, shields and an array of powerful defensive options, Shieldbearers are often hard to defeat even without a healer by their side.",

    ["Hexxer"] = "All shaman and witch doctors know of ways to invoke spirits to do their bidding. The hexxer (or Swamp Witch) takes this craft to a new level, calling the wrath of spirits down upon his enemies. With a dance and a chant, he weakens and debilitates his foes. Hexxers are particularly skilled at all crafting and performing (chant, dance). Most people see hexxers as mysterious and perhaps a little disturbed, especially since hexxer pastime and performances are bizarre.",

    ["Twilight Cultist"] = "Twilight's Hammer is a nihilist quasi-religious sect active across Azeroth that fanatically serves and worships the Old Gods and seeks to bring about the end of the world. Originally founded by Cho'gall as a clan of pale orcs, the cult has been active since before the First War but became a major worldwide threat.",
}
