#!/usr/bin/env python3
"""
Scrape WoW Classic equippable item IDs from Wowhead by source type.
Generates ItemSourceData.lua.

Wowhead source filter (filter=128;VALUE;0):
    3 = Crafted
    4 = Drop
    6 = Quest
    7 = Vendor

Split by 5-level ranges to stay under Wowhead's 1000-item display cap.

Usage:
    pip install playwright
    python -m playwright install chromium
    python scrape_wowhead_playwright.py
"""

import os, sys, time, json, re, math
from datetime import datetime

try:
    from playwright.sync_api import sync_playwright
except ImportError:
    print("Run: pip install playwright && python -m playwright install chromium")
    sys.exit(1)

DELAY = 3
LEVEL_RANGES = [(i, i + 4) for i in range(0, 80, 5)]  # 0-4, 5-9, ..., 75-79

SOURCES = {
    "quest":   6,
    "vendor":  7,
    "crafted": 3,
    "drop":    4,
}

CATEGORIES = ["armor", "weapons"]


def extract_ids(page, url, label):
    """Load a Wowhead page and return a set of item IDs."""
    print(f"    {label} ... ", end="", flush=True)
    try:
        page.goto(url, wait_until="domcontentloaded", timeout=30000)
        page.wait_for_timeout(3500)
    except Exception as e:
        print(f"LOAD ERROR ({e})")
        return set()

    try:
        ids = page.evaluate("""
        () => {
            const ids = new Set();
            // Listview instances
            if (typeof Listview !== 'undefined' && Listview.instances) {
                for (const key in Listview.instances) {
                    const lv = Listview.instances[key];
                    if (lv && lv.data) {
                        lv.data.forEach(item => {
                            if (item && item.id) ids.add(item.id);
                        });
                    }
                }
            }
            // g_items fallback
            if (ids.size === 0 && typeof g_items !== 'undefined') {
                for (const id in g_items) ids.add(parseInt(id));
            }
            // WH.Gatherer fallback
            if (ids.size === 0 && typeof WH !== 'undefined' && WH.Gatherer && WH.Gatherer.data) {
                for (const t in WH.Gatherer.data) {
                    for (const id in WH.Gatherer.data[t]) {
                        const n = parseInt(id);
                        if (n > 0 && n < 100000) ids.add(n);
                    }
                }
            }
            return Array.from(ids);
        }
        """)
    except Exception as e:
        print(f"JS ERROR ({e})")
        return set()

    # Filter out NaN / non-finite values that JS parseInt can produce
    result = set()
    if ids:
        for v in ids:
            if isinstance(v, (int, float)) and not math.isnan(v) and v > 0:
                result.add(int(v))
    print(f"{len(result)}")
    return result


def scrape_source(page, source_name, source_filter):
    """Scrape all equippable items for one source type."""
    all_ids = set()

    for cat in CATEGORIES:
        print(f"\n  [{source_name}] {cat}:")
        for lmin, lmax in LEVEL_RANGES:
            url = (
                f"https://www.wowhead.com/classic/items/{cat}"
                f"/min-req-level:{lmin}/max-req-level:{lmax}"
                f"?filter=128;{source_filter};0"
            )
            ids = extract_ids(page, url, f"lv {lmin:2d}-{lmax:2d}")
            all_ids.update(ids)
            time.sleep(DELAY)

            # If we hit 1000, warn (shouldn't happen with 5-level ranges)
            if len(ids) >= 1000:
                print(f"    *** WARNING: 1000 cap hit for {cat} lv {lmin}-{lmax}! ***")

    return all_ids


# ---------------------------------------------------------------------------
# Lua generation
# ---------------------------------------------------------------------------

def fmt(ids, per_line=15):
    # Extra safety: filter out any non-integer / NaN that slipped through
    s = sorted(int(x) for x in ids if isinstance(x, (int, float)) and not math.isnan(x) and x > 0)
    lines = []
    for i in range(0, len(s), per_line):
        lines.append("    " + ",".join(str(x) for x in s[i:i+per_line]) + ",")
    return "\n".join(lines)


def generate_lua(quest, vendor, crafted, drop, path):
    lua = f"""----------------------------------------------------------------------
-- HardcoreClassesEnhanced — Item Source Data
--
-- AUTO-GENERATED by tools/scrape_wowhead_playwright.py
-- Date: {datetime.now().strftime("%Y-%m-%d %H:%M")}
-- Source: Wowhead Classic (https://www.wowhead.com/classic)
--
-- Quest reward items : {len(quest):,}
-- Vendor items       : {len(vendor):,}
-- Crafted items      : {len(crafted):,}
-- Looted (drop) items: {len(drop):,}
----------------------------------------------------------------------

HCE = HCE or {{}}
HCE.CuratedItems = HCE.CuratedItems or {{}}
HCE.CuratedComplete = HCE.CuratedComplete or {{}}

local C = HCE.CuratedItems
local COMPLETE = HCE.CuratedComplete

local function fill(tbl, ids)
    for i = 1, #ids do
        tbl[ids[i]] = true
    end
end

C.quest_rewards  = C.quest_rewards  or {{}}
C.vendor_items   = C.vendor_items   or {{}}
C.crafted_items  = C.crafted_items  or {{}}
C.looted_gear    = C.looted_gear    or {{}}

----------------------------------------------------------------------
-- QUEST REWARD ITEMS ({len(quest):,} items)
----------------------------------------------------------------------

fill(C.quest_rewards, {{
{fmt(quest)}
}})
COMPLETE["quest_rewards"] = true

----------------------------------------------------------------------
-- VENDOR-SOLD ITEMS ({len(vendor):,} items)
----------------------------------------------------------------------

fill(C.vendor_items, {{
{fmt(vendor)}
}})
COMPLETE["vendor_items"] = true

----------------------------------------------------------------------
-- CRAFTED ITEMS ({len(crafted):,} items)
----------------------------------------------------------------------

fill(C.crafted_items, {{
{fmt(crafted)}
}})
COMPLETE["crafted_items"] = true

----------------------------------------------------------------------
-- LOOTED / DROP ITEMS ({len(drop):,} items)
----------------------------------------------------------------------

fill(C.looted_gear, {{
{fmt(drop)}
}})
COMPLETE["looted_gear"] = true

----------------------------------------------------------------------
-- COMBINED SOURCE CHECKER
----------------------------------------------------------------------

function HCE.CheckItemSource(itemID)
    if not itemID then return false, nil end
    if C.vendor_items and C.vendor_items[itemID] then
        return true, "vendor"
    end
    if C.quest_rewards and C.quest_rewards[itemID] then
        return true, "quest reward"
    end
    if C.crafted_items and C.crafted_items[itemID] then
        return true, "crafted"
    end
    if C.looted_gear and C.looted_gear[itemID] then
        return true, "loot drop"
    end
    return false, nil
end

function HCE.IsLootDrop(itemID)
    if not itemID then return false end
    return C.looted_gear and C.looted_gear[itemID] or false
end

function HCE.AllSourceListsComplete()
    return COMPLETE["quest_rewards"]
       and COMPLETE["vendor_items"]
       and COMPLETE["crafted_items"]
       and COMPLETE["looted_gear"]
end

----------------------------------------------------------------------
-- ITEM SOURCE SLASH COMMAND HELPER
----------------------------------------------------------------------

local SLOT_NAMES = {{
    [1]  = "Head",     [2]  = "Neck",     [3]  = "Shoulder",
    [5]  = "Chest",    [6]  = "Waist",    [7]  = "Legs",
    [8]  = "Feet",     [9]  = "Wrist",    [10] = "Hands",
    [11] = "Ring 1",   [12] = "Ring 2",   [13] = "Trinket 1",
    [14] = "Trinket 2",[15] = "Back",     [16] = "Main Hand",
    [17] = "Off Hand", [18] = "Ranged",   [19] = "Tabard",
}}

local GEAR_SLOTS = {{
    1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
}}

local QUALITY_LABELS = {{
    [0] = "poor", [1] = "common", [2] = "uncommon",
    [3] = "rare", [4] = "epic",   [5] = "legendary",
}}

function HCE.PrintItemSources()
    if not HCE_CharDB or not HCE_CharDB.selectedCharacter then
        HCE.Print("No enhanced class selected.")
        return
    end

    HCE.Print("Item source breakdown (equipped gear):")
    local checked, unknown, vendorN, questN, craftedN, lootedN = 0, 0, 0, 0, 0, 0

    for _, slotID in ipairs(GEAR_SLOTS) do
        local itemID = GetInventoryItemID("player", slotID)
        if itemID then
            checked = checked + 1
            local name, _, quality = GetItemInfo(itemID)
            name = name or ("item:" .. itemID)
            quality = quality or 0
            local qLabel = QUALITY_LABELS[quality] or ("q" .. quality)
            local slotLabel = SLOT_NAMES[slotID] or ("Slot " .. slotID)

            if quality <= 1 then
                DEFAULT_CHAT_FRAME:AddMessage(
                    "  " .. slotLabel .. ": |cff888888" .. name ..
                    " (" .. qLabel .. ")|r — basic item"
                )
            else
                local found, source = HCE.CheckItemSource(itemID)
                if found then
                    if source == "vendor" then vendorN = vendorN + 1
                    elseif source == "quest reward" then questN = questN + 1
                    elseif source == "loot drop" then lootedN = lootedN + 1
                    else craftedN = craftedN + 1 end
                    DEFAULT_CHAT_FRAME:AddMessage(
                        "  " .. slotLabel .. ": |cff00ff00" .. name ..
                        "|r — " .. source
                    )
                else
                    unknown = unknown + 1
                    DEFAULT_CHAT_FRAME:AddMessage(
                        "  " .. slotLabel .. ": |cffffaa33" .. name ..
                        " (" .. qLabel .. ")|r — unknown source"
                    )
                end
            end
        end
    end

    HCE.Print(string.format(
        "Summary: %d checked — %d vendor, %d quest, %d crafted, %d looted, %d unknown",
        checked, vendorN, questN, craftedN, lootedN, unknown
    ))
end
"""
    with open(path, "w", encoding="utf-8") as f:
        f.write(lua)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print("=" * 60)
    print("Wowhead Classic Item Source Scraper")
    print(f"Level ranges: {len(LEVEL_RANGES)} x 2 categories x {len(SOURCES)} sources")
    print(f"= {len(LEVEL_RANGES) * 2 * len(SOURCES)} total page loads")
    print(f"Estimated time: ~{len(LEVEL_RANGES) * 2 * len(SOURCES) * (DELAY + 4) // 60} minutes")
    print("=" * 60)

    script_dir = os.path.dirname(os.path.abspath(__file__))
    output_path = os.path.join(script_dir, "..", "ItemSourceData.lua")

    with sync_playwright() as p:
        print("\nLaunching browser...")
        browser = p.chromium.launch(headless=True)
        context = browser.new_context(
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                       "AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36"
        )
        page = context.new_page()

        # Accept cookies
        print("Loading Wowhead...")
        try:
            page.goto("https://www.wowhead.com/classic", wait_until="domcontentloaded", timeout=30000)
            page.wait_for_timeout(2000)
            consent = page.query_selector('#onetrust-accept-btn-handler')
            if consent:
                consent.click()
                page.wait_for_timeout(1000)
        except Exception:
            pass

        # Quick test
        print("\nTest fetch...")
        test_ids = extract_ids(
            page,
            "https://www.wowhead.com/classic/items/armor/min-req-level:10/max-req-level:14?filter=128;6;0",
            "quest armor lv10-14"
        )
        time.sleep(DELAY)

        if not test_ids:
            print("ERROR: Test returned 0 items. Check debug output.")
            html = page.content()
            with open(os.path.join(script_dir, "debug_page.html"), "w") as f:
                f.write(html)
            browser.close()
            sys.exit(1)

        print(f"  Test OK — got {len(test_ids)} items\n")

        # Scrape each source
        results = {}
        for source_name, source_filter in SOURCES.items():
            print(f"\n{'=' * 60}")
            print(f"Scraping {source_name.upper()} (filter=128;{source_filter};0)")
            print(f"{'=' * 60}")
            results[source_name] = scrape_source(page, source_name, source_filter)
            print(f"\n  → {source_name} total: {len(results[source_name]):,} unique items")

        browser.close()

    # Summary
    print(f"\n{'=' * 60}")
    print("RESULTS")
    print(f"{'=' * 60}")
    for name, ids in results.items():
        print(f"  {name:10s}: {len(ids):>6,} items")

    # Save debug
    debug = {k: sorted(v) for k, v in results.items()}
    with open(os.path.join(script_dir, "debug_items.json"), "w") as f:
        json.dump(debug, f)

    # Generate Lua with all four source types
    generate_lua(results["quest"], results["vendor"], results["crafted"], results["drop"], output_path)
    print(f"\nGenerated: {output_path}")
    print("Done!")


if __name__ == "__main__":
    main()
